Repository MyGesDfu/Projet-Git, pull requests merged in 2025-02, with the labels that each got.

#30 Ajout de la documentation LICENSE.md
  LICENSE.md
  READ.md
Labels: documentation

#28 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature

#27 Feature/template issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/default.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature

#33 Ajout d'un template pour les pull requests
  .github/workflows/ISSUE_TEMPLATE/pull_request_template.md
Labels: feature

#45 Feature/auto suggestion
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/src/autosuggest.js
Labels: feature

#44 Feature/form preview before submission
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/src/form.html
  .github/src/previw.js
Labels: feature

#43 correction chargement image
  .github/src/image.js
Labels: bug

#46 Bug/erreur500
  .github/src/form-handler.js
Labels: bug
